apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: kubelet-psp
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:nodes
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: kubelet-psp
