apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kubelet-psp
spec:
  hostNetwork: true
  privileged: true
  hostPID: true
  hostIPC: true
  hostPorts:
  - min: 1
    max: 65534
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
